UBUNTU: SAUCE: apparmor4.0.0 [35/58]: 6.15 apparmor-next: apparmor: Fix checking address of an array in accum_label_info()
BugLink: http://bugs.launchpad.net/bugs/2028253

clang warns:

  security/apparmor/label.c:206:15: error: address of array 'new->vec' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
    206 |         AA_BUG(!new->vec);
        |                ~~~~~~^~~

The address of this array can never be NULL because it is not at the
beginning of a structure. Convert the assertion to check that the new
pointer is not NULL.

Fixes: de4754c801f4 ("apparmor: carry mediation check on label")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202501191802.bDp2voTJ-lkp@intel.com/
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: John Johansen <john.johansen@canonical.com>
(cherry picked from commit 6067d4425bdb8be02a2b52352e8bbf08fe27e667 https://git.launchpad.net/~apparmor-dev/ubuntu-kernel-next v6.13-apparmor-plucky)
Signed-off-by: John Cabaj <john.cabaj@canonical.com>