rust: bindgen: Make snd_dec_flac opaque
At least with certain some rust / bindgen combinations compilation fails
with:

error[E0587]: type has conflicting packed and align representation hints
      --> /Transit/build/linux/rust/bindings/bindings_generated.rs:102244:1
       |
102244 | pub struct snd_dec_flac {
       | ^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Janne Grunau <j@jannau.net>
(cherry picked from commit b969cc36ebd0e8c0d99894a64e81cf7edbe554bd https://github.com/AsahiLinux/linux)
Signed-off-by: Vinicius Peixoto <vinicius.peixoto@canonical.com>