UBUNTU: SAUCE: apparmor4.0.0 [39/58]: 6.15 apparmor-next: apparmor: use the condition in AA_BUG_FMT even with debug disabled
BugLink: http://bugs.launchpad.net/bugs/2028253

This follows the established practice and fixes a build failure for me:
security/apparmor/file.c: In function ‘__file_sock_perm’:
security/apparmor/file.c:544:24: error: unused variable ‘sock’ [-Werror=unused-variable]
  544 |         struct socket *sock = (struct socket *) file->private_data;
      |                        ^~~~

Signed-off-by: Mateusz Guzik <mjguzik@gmail.com>
Signed-off-by: John Johansen <john.johansen@canonical.com>
(cherry picked from commit 95655c5f2d25b37e2e7a7bf668a68daff6471691 https://git.launchpad.net/~apparmor-dev/ubuntu-kernel-next v6.13-apparmor-plucky)
Signed-off-by: John Cabaj <john.cabaj@canonical.com>